### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by kiuX89** [hamnsk/vmware-exporter#4]
Hello, I'm interested in your project and I tried to install it with the .deb file. 
I downloaded the binary and wanted to make a systemd : 
```

[Unit]
Description=VMware Exporter
After=network.target

[Service]
Type=simple
ExecStart=/opt/prometheus/exporters/vmware-exporter/vmware-exporter
EnvironmentFile=/opt/prometheus/exporters/vmware-exporter/config.env
[Install]
WantedBy=multi-user.target

```

vmware exporter launches and after a few seconds it stops. do you have any documentation on how to install it? or can you tell me where I'm going wrong? I'll send you the logs and my config file. 
thank you :)

log : 

```
× vmware_exporter.service - VMware Exporter
     Loaded: loaded (/etc/systemd/system/vmware_exporter.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-04-10 14:45:25 CEST; 12min ago
   Duration: 13.454s
    Process: 39493 ExecStart=/opt/prometheus/exporters/vmware-exporter/vmware-exporter (code=exited, status=2)
   Main PID: 39493 (code=exited, status=2)
        CPU: 31ms

avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]: vmware-exporter/internal/vmware.(*service).status(0xc00037e040)
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]:         /home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/service.go:112 +0x722
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]: vmware-exporter/internal/vmware.Collector.Collect({{0x1247b60, 0xc00037e040}, 0xc0003789a0, 0xc000378a10, 0xc000378a80, 0xc000378af0, 0xc00037>
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]:         /home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/collector.go:1443 +0x52
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456 +0xfb
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
avril 10 14:45:25 VictoriaMetrics vmware-exporter[39493]:         /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:467 +0x565
avril 10 14:45:25 VictoriaMetrics systemd[1]: vmware_exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
avril 10 14:45:25 VictoriaMetrics systemd[1]: vmware_exporter.service: Failed with result 'exit-code'.
```
config.env : 

```
VMWARE_EXPORTER_BIND_ADDR=127.0.0.1:9513
VMWARE_EXPORTER_VMWARE_USER=XXXXXXXXXXXXXX
VMWARE_EXPORTER_VMWARE_PASSWORD=XXXXXXXXXXXXXXXXXX
VMWARE_EXPORTER_LOG_LEVEL=info
VMWARE_EXPORTER_HTTP_WRITE_TIMEOUT=30s
VMWARE_EXPORTER_HTTP_READ_TIMEOUT=30s
```

**Comment by hamnsk** [comment]
There was a bug in the code related to inactive links on the hypervisor, I fixed this bug and added the code to the develop branch. Try to build the binary from there.

Also the latest version of the code works with Hashicortp Vault, which is considered more basic. Here are the envs that I pass when I use it:

VMWARE_EXPORTER_BIND_ADDR=:9155;
VMWARE_EXPORTER_HTTP_READ_TIMEOUT=30s;
VMWARE_EXPORTER_HTTP_WRITE_TIMEOUT=30s;
VMWARE_EXPORTER_LOG_LEVEL=info;
VMWARE_EXPORTER_USE_VAULT=true;
VMWARE_EXPORTER_VAULT_ADDR=https://vault.addr.here:8080;
VMWARE_EXPORTER_VAULT_AUTH_NAME=approle;
VMWARE_EXPORTER_EXPORTER_VAULT_ROLE_ID=role-id;
VMWARE_EXPORTER_VAULT_SECRET_STORE_NAME=secrets;
VMWARE_EXPORTER_VAULT_SECRET_STORE_PATH=infra/esxi/monitoring;

These two variables are only used when you have 1 host, but even then I would recommend using Vault
VMWARE_EXPORTER_VMWARE_PASSWORD=pass;
VMWARE_EXPORTER_VMWARE_USER=user


I hope this helps you, if not, send me a more complete log, I'll try to run it like you did and see what's wrong.

**Comment by hamnsk** [comment]
I ran the code in a similar configuration and here is my log:

```
GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/s.andryunin/go #gosetup
/usr/local/opt/go/libexec/bin/go build -o /Users/s.andryunin/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___1go_build_vmware_exporter_cmd_vmware_exporter vmware-exporter/cmd/vmware-exporter #gosetup
/Users/s.andryunin/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___1go_build_vmware_exporter_cmd_vmware_exporter
{"level":"INFO","timestamp":"2024-04-10T22:22:17.977+0300","caller":"app/app.go:75","message":"Start application...","version":"unset","build_time":"unset","commit":"unset"}
{"level":"INFO","timestamp":"2024-04-10T22:22:17.978+0300","caller":"app/app.go:81","message":"Application logger initialized."}
{"level":"INFO","timestamp":"2024-04-10T22:22:17.978+0300","caller":"app/app.go:83","message":"Application router initialized."}
{"level":"INFO","timestamp":"2024-04-10T22:22:17.978+0300","caller":"app/app.go:111","message":"Starting server...","bind_addr":":9155"}
```

After that I made a request in my browser to the following address:

http://localhost:9155/probe?target=192.168.1.30

Where I specified the IP address of my hypervisor, and login and password were specified in the env parameters, and the browser received the output, the output is intentionally abbreviated:

```
# HELP vmware_exporter_datastore_capacity_size Datastore total
# TYPE vmware_exporter_datastore_capacity_size gauge
vmware_exporter_datastore_capacity_size{ds_name="datastore1",host_name="1esxi0001.k11s.cloud.vsk.local"} 1.38781130752e+11
vmware_exporter_datastore_capacity_size{ds_name="iso-store01t",host_name="1esxi0001.k11s.cloud.vsk.local"} 1.07105746944e+11
vmware_exporter_datastore_capacity_size{ds_name="sas1tb",host_name="1esxi0001.k11s.cloud.vsk.local"} 9.999220736e+11
vmware_exporter_datastore_capacity_size{ds_name="templates",host_name="1esxi0001.k11s.cloud.vsk.local"} 5.36602476544e+11
# HELP vmware_exporter_datastore_freespace_size Datastore free
# TYPE vmware_exporter_datastore_freespace_size gauge
vmware_exporter_datastore_freespace_size{ds_name="datastore1",host_name="1esxi0001.k11s.cloud.vsk.local"} 1.36249868288e+11
vmware_exporter_datastore_freespace_size{ds_name="iso-store01t",host_name="1esxi0001.k11s.cloud.vsk.local"} 1.8856542208e+10
vmware_exporter_datastore_freespace_size{ds_name="sas1tb",host_name="1esxi0001.k11s.cloud.vsk.local"} 6.28982022144e+11
vmware_exporter_datastore_freespace_size{ds_name="templates",host_name="1esxi0001.k11s.cloud.vsk.local"} 2.21299867648e+11
# HELP vmware_exporter_host_boot_timestamp_seconds Uptime host
# TYPE vmware_exporter_host_boot_timestamp_seconds gauge
vmware_exporter_host_boot_timestamp_seconds{host_name="1esxi0001.k11s.cloud.vsk.local"} 1.709125112e+09
# HELP vmware_exporter_host_cpu_cores Vmware Host CPU Cores
# TYPE vmware_exporter_host_cpu_cores gauge
vmware_exporter_host_cpu_cores{host_name="1esxi0001.k11s.cloud.vsk.local"} 12
# HELP vmware_exporter_host_cpu_max CPU total
# TYPE vmware_exporter_host_cpu_max gauge
vmware_exporter_host_cpu_max{host_name="1esxi0001.k11s.cloud.vsk.local"} 35196
# HELP vmware_exporter_host_cpu_mhz Vmware Host CPU Mhz
# TYPE vmware_exporter_host_cpu_mhz gauge
vmware_exporter_host_cpu_mhz{host_name="1esxi0001.k11s.cloud.vsk.local"} 2933
# HELP vmware_exporter_host_cpu_threads Vmware Host CPU Threads
# TYPE vmware_exporter_host_cpu_threads gauge
vmware_exporter_host_cpu_threads{host_name="1esxi0001.k11s.cloud.vsk.local"} 24
# HELP vmware_exporter_host_cpu_usage CPU Usage
# TYPE vmware_exporter_host_cpu_usage gauge
vmware_exporter_host_cpu_usage{host_name="1esxi0001.k11s.cloud.vsk.local"} 740
# HELP vmware_exporter_host_disk_ok Disk is working normally
# TYPE vmware_exporter_host_disk_ok gauge
vmware_exporter_host_disk_ok{device="/vmfs/devices/cdrom/mpx.vmhba0:C0:T0:L0",host_name="1esxi0001.k11s.cloud.vsk.local"} 1
vmware_exporter_host_disk_ok{device="/vmfs/devices/disks/naa.600140590eda987d80340b2abed9ba4d",host_name="1esxi0001.k11s.cloud.vsk.local"} 0
vmware_exporter_host_disk_ok{device="/vmfs/devices/disks/naa.6001405a01d6c40e201477ea4ac3ec44",host_name="1esxi0001.k11s.cloud.vsk.local"} 0
vmware_exporter_host_disk_ok{device="/vmfs/devices/disks/naa.600508b1001c1bc33eed5e085701c80e",host_name="1esxi0001.k11s.cloud.vsk.local"} 1
vmware_exporter_host_disk_ok{device="/vmfs/devices/disks/naa.600508b1001ca899238bf0f48c438a92",host_name="1esxi0001.k11s.cloud.vsk.local"} 1
# HELP vmware_exporter_host_hardware_info Vmware Host Hardware info
```

My env settings is:

```
VMWARE_EXPORTER_BIND_ADDR=:9155
VMWARE_EXPORTER_HTTP_READ_TIMEOUT=30s
VMWARE_EXPORTER_HTTP_WRITE_TIMEOUT=30s
VMWARE_EXPORTER_LOG_LEVEL=info
VMWARE_EXPORTER_USE_VAULT=false
VMWARE_EXPORTER_VMWARE_PASSWORD=passw0rd
VMWARE_EXPORTER_VMWARE_USER=usEr
```

**Comment by hamnsk** [comment]
I've added the code to the main branch and made a new release, hope this helps you, if not, I'm waiting for a more complete log from you.

**Comment by kiuX89** [comment]
Hello, 
thank you for your reply, I've just installed your latest update and it's much better :)

I put this in my configuration file : 
```
VMWARE_EXPORTER_BIND_ADDR=:9513
VMWARE_EXPORTER_VMWARE_USER=USER
VMWARE_EXPORTER_VMWARE_PASSWORD=P@ssword1234
VMWARE_EXPORTER_LOG_LEVEL=info
VMWARE_EXPORTER_HTTP_WRITE_TIMEOUT=30s
VMWARE_EXPORTER_HTTP_READ_TIMEOUT=30s
VMWARE_EXPORTER_USE_VAULT=false
```

but I don't have access to my metrics: 
```
{"level":"INFO","timestamp":"2024-04-11T10:11:47.670+0200","caller":"app/app.go:75","message":"Start application...","version":"0.5.1","build_time":"2024-04-10T19:39:39Z","commit":"44c8a25a1d94d45134f980173a48a627060e5fa5"}
{"level":"INFO","timestamp":"2024-04-11T10:11:47.670+0200","caller":"app/app.go:81","message":"Application logger initialized."}
{"level":"INFO","timestamp":"2024-04-11T10:11:47.670+0200","caller":"app/app.go:83","message":"Application router initialized."}
{"level":"INFO","timestamp":"2024-04-11T10:11:47.670+0200","caller":"app/app.go:111","message":"Starting server...","bind_addr":":9513"}
{"level":"ERROR","timestamp":"2024-04-11T10:11:55.201+0200","caller":"logging/logging.go:53","message":"ServerFaultCode: Permission to perform this operation was denied.","stacktrace":"vmware-exporter/pkg/logging.(*Logger).Error\n\t/home/runner/work/vmware-exporter/vmware-exporter/pkg/logging/logging.go:53\nvmware-exporter/internal/vmware.(*service).status\n\t/home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/service.go:91\nvmware-exporter/internal/vmware.Collector.Collect\n\t/home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/collector.go:1443\ngithub.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1\n\t/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456"}
{"level":"ERROR","timestamp":"2024-04-11T10:11:55.201+0200","caller":"logging/logging.go:53","message":"failed collecting VMWare metrics: ServerFaultCode: Permission to perform this operation was denied.","stacktrace":"vmware-exporter/pkg/logging.(*Logger).Error\n\t/home/runner/work/vmware-exporter/vmware-exporter/pkg/logging/logging.go:53\nvmware-exporter/internal/vmware.(*service).error\n\t/home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/service.go:64\nvmware-exporter/internal/vmware.Collector.Collect\n\t/home/runner/work/vmware-exporter/vmware-exporter/internal/vmware/collector.go:1446\ngithub.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1\n\t/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456"}
```
Do I need to do anything on my esxi? 
sincerely

**Comment by hamnsk** [comment]
Try in env to add root login and password, or that account to add all read permissions, right now there are not enough permissions on the hypervisor.

**Comment by kiuX89** [comment]
I already have my root user and password :/.

**Comment by hamnsk** [comment]
![Screenshot 2024-04-11 at 12 24 50](https://github.com/hamnsk/vmware-exporter/assets/15730393/de7eada8-3fb7-41ba-9bc8-585d295e4e4b)
![Screenshot 2024-04-11 at 12 24 56](https://github.com/hamnsk/vmware-exporter/assets/15730393/a6121eee-5ca1-445c-8fe4-33d701f68522)
![Screenshot 2024-04-11 at 12 25 12](https://github.com/hamnsk/vmware-exporter/assets/15730393/649312bb-9cb8-4562-a4af-71d46257e094)
![Screenshot 2024-04-11 at 12 25 20](https://github.com/hamnsk/vmware-exporter/assets/15730393/9c9f56c3-029a-4fbc-9bf6-5b8d6905f8ab)

**Comment by hamnsk** [comment]
```
failed collecting VMWare metrics: ServerFaultCode: Permission to perform this operation was denied.
```

This error returned from esxi

**Comment by kiuX89** [comment]
I'm root in my configuration file and I still get the same message.

**Comment by hamnsk** [comment]
Try running it under debug to see which metric build it crashed on. Because I have 4 servers in different configurations and all worked. But I have version 6.7 maybe you have a different version? Or some other hardware is disabled, to which the library reacts in such a way and returns an error.

**Comment by kiuX89** [comment]
In fact, I think it was my victoriametrics configuration that was causing the problem. Now everything's working properly and I can get my metrics :) For your information, I'm on esxi 8. 

do you think you'll upgrade your project to support vcenter?

**Comment by hamnsk** [comment]
Great, glad it worked for you and we figured out the settings and how the exporter works. As for the VCenter support, I don't have a license to use it at the moment, maybe in the future I'll try to work on it with the trial version.

**Comment by wipphj** [comment]
Hello, I also encountered the same problem. How did you solve it? I deployed it using docker, which is the latest version. esxi is version 7.0.3, and the account is the root account. The error is also reported at `/client_golang@v1.14.0/prometheus/registry.go:456`
 thank you

**Comment by hamnsk** [comment]
Should be fixed, the problem occurred when network interfaces were not connected, I have no opportunity to test the exporter on version 7.0.3 unfortunately. Try to connect all available network interfaces to the network, if this helps, I will try to make a fix.

**Comment by wipphj** [comment]
Thanks for your response. I'm a bit unclear about the `network interfaces were not connected` issue you mentioned. Could you clarify whether you're referring to the network interfaces of the container or the ESXi host?
I've tried running the binary directly on a Linux host machine and accessing the address via web browser `http://hostip:9155/probe?target=192.168.123.10`. However, I'm getting a 500 error on the web interface, and the backend logs show the error I included in my previous reply.
Interestingly, I can successfully access the ESXi API using Postman with the following request: `POST https://192.168.123.10/sdk`.
Here's another piece of information that might be relevant to the network interface issue: When I change the target in the URL `http://hostip:9155/probe?target=192.168.123.10` to a non-existent address, the error messages on both the web interface and the backend are the same. Does this mean that the ESXi host is not being found?
If that's the case, my ESXi host only has one IP address configured; there are no other network interfaces (or perhaps I haven't understood correctly).

Just to confirm, I'm using an ESXi host, not vCenter.

![Image](https://github.com/user-attachments/assets/32a71ea2-3e8c-48d4-8a5d-d0ba24b2aa24)

In any case, thank you for your reply!

**Comment by hamnsk** [comment]
Send screenshots of errors, the exporter itself does not poll anything until we come with a GET request at the address /probe, the exporter itself has its own metrics available at the address /matrics, try checking if the metrics are available? If you have the same error with an existing and non-existent host, there may be a situation in incorrectly specified settings for authorization. The thing is that I prefer to store secrets in Vault and the exporter is more tailored for this approach, but you can pass them through environment variables. Send me the environment parameters, how you run the exporter. It actually does not matter to him where to work in a container or on a host machine, it will work the same way. When I wrote about network interfaces, there was a problem that if not all interfaces on the host with the ESXI were connected to the network, an error occurred, this error was the reason for the ticket being opened initially, now the problem has been fixed, most likely your reason is different. But to understand this, you need to at least know how you launch the exporter.

And please translate your system into English, otherwise we will be looking for understanding for a very long time. For me, pictures in Chinese mean nothing, or Japanese, or any other language.

**Comment by wipphj** [comment]
Thank you, I will add more information. Below is the screenshot I started through docker, including `probe` and `metrics`
![Image](https://github.com/user-attachments/assets/c9e609bb-506a-48d7-98bc-9125f40e0065)


Startup logs and error messages of backend services
![Image](https://github.com/user-attachments/assets/b81723e2-ecc0-4d0d-b265-1cc2f04ba00b)

Additionally, it's worth mentioning that when accessing the ESXi address in a browser, a warning about the certificate being untrusted will appear.

![Image](https://github.com/user-attachments/assets/d69704ce-f6b9-4345-800f-a7a02bda675b)

Below is some information about my docker-compose

```
vmware_exporter:
    container_name: vmware_exporter
    image: ghcr.io/hamnsk/vmware-exporter:0.5.2
    environment:
      - 'VMWARE_EXPORTER_BIND_ADDR=0.0.0.0:9513'
      - VMWARE_EXPORTER_VMWARE_USER=root
      - VMWARE_EXPORTER_VMWARE_PASSWORD=XXXXX
      - VMWARE_EXPORTER_USE_VAULT=false
      - VMWARE_EXPORTER_LOG_LEVEL=debug
      - VMWARE_EXPORTER_HTTP_WRITE_TIMEOUT=30s
      - VMWARE_EXPORTER_HTTP_READ_TIMEOUT=30s
      - VMWARE_EXPORTER_SCRAPE_TIMEOUT=30s
    restart: unless-stopped
    ports:
      - 9513:9513
    networks:
      - netw

networks:
  netw:
    external: true

```

**Comment by wipphj** [comment]
I identified the cause of the previous error, `context deadline exceeded`. It was due to the `VMWARE_EXPORTER_SCRAPE_TIMEOUT `being set too low. I adjusted it to `30000s`, and that resolved the issue.

However, I am now facing another problem where the error indicates that the metric does not exist. Could you please clarify whether this is due to a configuration that needs to be enabled on the ESXi host or if there is another reason for this issue (see the attached error screenshot)? Thank you!

![Image](https://github.com/user-attachments/assets/073f0f03-f08b-4af8-ae74-dcec360882b0)

**Comment by hamnsk** [comment]
Judging by your posts above, you are not installing the hypervisor on server hardware, so SDK does not provide this information, I will try to fix this by adding a check for non-existent records. Thanks for such a detailed report.

**Comment by hamnsk** [comment]
Please use this release https://github.com/hamnsk/vmware-exporter/releases/tag/0.5.3
May be a fixed your problem

**Comment by wipphj** [comment]
> Please use this release https://github.com/hamnsk/vmware-exporter/releases/tag/0.5.3 May be a fixed your problem

thanks
